#!/bin/sh

repeat() {
    result=""
    cnt=0
    while [ $cnt -lt "$2" ]; do
        result="$result$1"
        cnt=$((cnt + 1))
    done
    echo "$result"
}

column_num=$(tput cols)
column_num=$((column_num - 10))
day=$(date +%j)
black=$((column_num * day / 365))
white=$((column_num - black))
bar="$((100 * day / 365))% [$(repeat '#' $black)$(repeat ' ' $white)]"
echo "$bar"
